//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDocPortuaria
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ServiceDocPortuaria.DocPortuariaSoap")]
    public interface DocPortuariaSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodCliente del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaTasa", ReplyAction="*")]
        ServiceDocPortuaria.CalculaTasaResponse CalculaTasa(ServiceDocPortuaria.CalculaTasaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaTasa", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaResponse> CalculaTasaAsync(ServiceDocPortuaria.CalculaTasaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodCliente del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaTasaT0", ReplyAction="*")]
        ServiceDocPortuaria.CalculaTasaT0Response CalculaTasaT0(ServiceDocPortuaria.CalculaTasaT0Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaTasaT0", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaT0Response> CalculaTasaT0Async(ServiceDocPortuaria.CalculaTasaT0Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CodCliente del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaTasaT1", ReplyAction="*")]
        ServiceDocPortuaria.CalculaTasaT1Response CalculaTasaT1(ServiceDocPortuaria.CalculaTasaT1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CalculaTasaT1", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaT1Response> CalculaTasaT1Async(ServiceDocPortuaria.CalculaTasaT1Request request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Puerto del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltaBerman", ReplyAction="*")]
        ServiceDocPortuaria.AltaBermanResponse AltaBerman(ServiceDocPortuaria.AltaBermanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AltaBerman", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.AltaBermanResponse> AltaBermanAsync(ServiceDocPortuaria.AltaBermanRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Puerto del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NuevoAltaBerman", ReplyAction="*")]
        ServiceDocPortuaria.NuevoAltaBermanResponse NuevoAltaBerman(ServiceDocPortuaria.NuevoAltaBermanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NuevoAltaBerman", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.NuevoAltaBermanResponse> NuevoAltaBermanAsync(ServiceDocPortuaria.NuevoAltaBermanRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fichero del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Firma_Documento", ReplyAction="*")]
        ServiceDocPortuaria.Firma_DocumentoResponse Firma_Documento(ServiceDocPortuaria.Firma_DocumentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Firma_Documento", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.Firma_DocumentoResponse> Firma_DocumentoAsync(ServiceDocPortuaria.Firma_DocumentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fichero del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioFTP", ReplyAction="*")]
        ServiceDocPortuaria.EnvioFTPResponse EnvioFTP(ServiceDocPortuaria.EnvioFTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioFTP", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.EnvioFTPResponse> EnvioFTPAsync(ServiceDocPortuaria.EnvioFTPRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fichero del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioDuePort", ReplyAction="*")]
        ServiceDocPortuaria.EnvioDuePortResponse EnvioDuePort(ServiceDocPortuaria.EnvioDuePortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnvioDuePort", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.EnvioDuePortResponse> EnvioDuePortAsync(ServiceDocPortuaria.EnvioDuePortRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetMessagesDuePortResult del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesDuePort", ReplyAction="*")]
        ServiceDocPortuaria.GetMessagesDuePortResponse GetMessagesDuePort(ServiceDocPortuaria.GetMessagesDuePortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesDuePort", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.GetMessagesDuePortResponse> GetMessagesDuePortAsync(ServiceDocPortuaria.GetMessagesDuePortRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento fichero del espacio de nombres http://tempuri.org no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageDuePort", ReplyAction="*")]
        ServiceDocPortuaria.SendMessageDuePortResponse SendMessageDuePort(ServiceDocPortuaria.SendMessageDuePortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageDuePort", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceDocPortuaria.SendMessageDuePortResponse> SendMessageDuePortAsync(ServiceDocPortuaria.SendMessageDuePortRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaTasaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaTasa", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.CalculaTasaRequestBody Body;
        
        public CalculaTasaRequest()
        {
        }
        
        public CalculaTasaRequest(ServiceDocPortuaria.CalculaTasaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class CalculaTasaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Escala;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int AñoEscala;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Operacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tasa;
        
        public CalculaTasaRequestBody()
        {
        }
        
        public CalculaTasaRequestBody(string CodCliente, int Escala, int AñoEscala, string Operacion, string Tasa)
        {
            this.CodCliente = CodCliente;
            this.Escala = Escala;
            this.AñoEscala = AñoEscala;
            this.Operacion = Operacion;
            this.Tasa = Tasa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaTasaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaTasaResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.CalculaTasaResponseBody Body;
        
        public CalculaTasaResponse()
        {
        }
        
        public CalculaTasaResponse(ServiceDocPortuaria.CalculaTasaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class CalculaTasaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculaTasaResult;
        
        public CalculaTasaResponseBody()
        {
        }
        
        public CalculaTasaResponseBody(double CalculaTasaResult)
        {
            this.CalculaTasaResult = CalculaTasaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaTasaT0Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaTasaT0", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.CalculaTasaT0RequestBody Body;
        
        public CalculaTasaT0Request()
        {
        }
        
        public CalculaTasaT0Request(ServiceDocPortuaria.CalculaTasaT0RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class CalculaTasaT0RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CodIMO;
        
        public CalculaTasaT0RequestBody()
        {
        }
        
        public CalculaTasaT0RequestBody(string CodCliente, string CodIMO)
        {
            this.CodCliente = CodCliente;
            this.CodIMO = CodIMO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaTasaT0Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaTasaT0Response", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.CalculaTasaT0ResponseBody Body;
        
        public CalculaTasaT0Response()
        {
        }
        
        public CalculaTasaT0Response(ServiceDocPortuaria.CalculaTasaT0ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class CalculaTasaT0ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculaTasaT0Result;
        
        public CalculaTasaT0ResponseBody()
        {
        }
        
        public CalculaTasaT0ResponseBody(double CalculaTasaT0Result)
        {
            this.CalculaTasaT0Result = CalculaTasaT0Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaTasaT1Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaTasaT1", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.CalculaTasaT1RequestBody Body;
        
        public CalculaTasaT1Request()
        {
        }
        
        public CalculaTasaT1Request(ServiceDocPortuaria.CalculaTasaT1RequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class CalculaTasaT1RequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CodCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Escala;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int AñoEscala;
        
        public CalculaTasaT1RequestBody()
        {
        }
        
        public CalculaTasaT1RequestBody(string CodCliente, int Escala, int AñoEscala)
        {
            this.CodCliente = CodCliente;
            this.Escala = Escala;
            this.AñoEscala = AñoEscala;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculaTasaT1Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculaTasaT1Response", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.CalculaTasaT1ResponseBody Body;
        
        public CalculaTasaT1Response()
        {
        }
        
        public CalculaTasaT1Response(ServiceDocPortuaria.CalculaTasaT1ResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class CalculaTasaT1ResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculaTasaT1Result;
        
        public CalculaTasaT1ResponseBody()
        {
        }
        
        public CalculaTasaT1ResponseBody(double CalculaTasaT1Result)
        {
            this.CalculaTasaT1Result = CalculaTasaT1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaBermanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaBerman", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.AltaBermanRequestBody Body;
        
        public AltaBermanRequest()
        {
        }
        
        public AltaBermanRequest(ServiceDocPortuaria.AltaBermanRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class AltaBermanRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Escala;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Año;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Puerto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Modificada;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CodigoBGM;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Practicaje;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Electricidad;
        
        public AltaBermanRequestBody()
        {
        }
        
        public AltaBermanRequestBody(int Escala, int Año, string Puerto, bool Modificada, int CodigoBGM, int Practicaje, int Electricidad)
        {
            this.Escala = Escala;
            this.Año = Año;
            this.Puerto = Puerto;
            this.Modificada = Modificada;
            this.CodigoBGM = CodigoBGM;
            this.Practicaje = Practicaje;
            this.Electricidad = Electricidad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AltaBermanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AltaBermanResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.AltaBermanResponseBody Body;
        
        public AltaBermanResponse()
        {
        }
        
        public AltaBermanResponse(ServiceDocPortuaria.AltaBermanResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class AltaBermanResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AltaBermanResult;
        
        public AltaBermanResponseBody()
        {
        }
        
        public AltaBermanResponseBody(string AltaBermanResult)
        {
            this.AltaBermanResult = AltaBermanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NuevoAltaBermanRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NuevoAltaBerman", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.NuevoAltaBermanRequestBody Body;
        
        public NuevoAltaBermanRequest()
        {
        }
        
        public NuevoAltaBermanRequest(ServiceDocPortuaria.NuevoAltaBermanRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class NuevoAltaBermanRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Escala;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Año;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Puerto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool Modificada;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int CodigoBGM;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int N_Atraque;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string TipoAtraque;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime Ocupacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.DateTime Desocupacion;
        
        public NuevoAltaBermanRequestBody()
        {
        }
        
        public NuevoAltaBermanRequestBody(int Escala, int Año, string Puerto, bool Modificada, int CodigoBGM, int N_Atraque, string TipoAtraque, System.DateTime Ocupacion, System.DateTime Desocupacion)
        {
            this.Escala = Escala;
            this.Año = Año;
            this.Puerto = Puerto;
            this.Modificada = Modificada;
            this.CodigoBGM = CodigoBGM;
            this.N_Atraque = N_Atraque;
            this.TipoAtraque = TipoAtraque;
            this.Ocupacion = Ocupacion;
            this.Desocupacion = Desocupacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NuevoAltaBermanResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NuevoAltaBermanResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.NuevoAltaBermanResponseBody Body;
        
        public NuevoAltaBermanResponse()
        {
        }
        
        public NuevoAltaBermanResponse(ServiceDocPortuaria.NuevoAltaBermanResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class NuevoAltaBermanResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NuevoAltaBermanResult;
        
        public NuevoAltaBermanResponseBody()
        {
        }
        
        public NuevoAltaBermanResponseBody(string NuevoAltaBermanResult)
        {
            this.NuevoAltaBermanResult = NuevoAltaBermanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Firma_DocumentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Firma_Documento", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.Firma_DocumentoRequestBody Body;
        
        public Firma_DocumentoRequest()
        {
        }
        
        public Firma_DocumentoRequest(ServiceDocPortuaria.Firma_DocumentoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class Firma_DocumentoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fichero;
        
        public Firma_DocumentoRequestBody()
        {
        }
        
        public Firma_DocumentoRequestBody(string fichero)
        {
            this.fichero = fichero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Firma_DocumentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Firma_DocumentoResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.Firma_DocumentoResponseBody Body;
        
        public Firma_DocumentoResponse()
        {
        }
        
        public Firma_DocumentoResponse(ServiceDocPortuaria.Firma_DocumentoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class Firma_DocumentoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Firma_DocumentoResult;
        
        public Firma_DocumentoResponseBody()
        {
        }
        
        public Firma_DocumentoResponseBody(string Firma_DocumentoResult)
        {
            this.Firma_DocumentoResult = Firma_DocumentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioFTPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioFTP", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.EnvioFTPRequestBody Body;
        
        public EnvioFTPRequest()
        {
        }
        
        public EnvioFTPRequest(ServiceDocPortuaria.EnvioFTPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class EnvioFTPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fichero;
        
        public EnvioFTPRequestBody()
        {
        }
        
        public EnvioFTPRequestBody(string fichero)
        {
            this.fichero = fichero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioFTPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioFTPResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.EnvioFTPResponseBody Body;
        
        public EnvioFTPResponse()
        {
        }
        
        public EnvioFTPResponse(ServiceDocPortuaria.EnvioFTPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class EnvioFTPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnvioFTPResult;
        
        public EnvioFTPResponseBody()
        {
        }
        
        public EnvioFTPResponseBody(string EnvioFTPResult)
        {
            this.EnvioFTPResult = EnvioFTPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioDuePortRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioDuePort", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.EnvioDuePortRequestBody Body;
        
        public EnvioDuePortRequest()
        {
        }
        
        public EnvioDuePortRequest(ServiceDocPortuaria.EnvioDuePortRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class EnvioDuePortRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fichero;
        
        public EnvioDuePortRequestBody()
        {
        }
        
        public EnvioDuePortRequestBody(string fichero)
        {
            this.fichero = fichero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioDuePortResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioDuePortResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.EnvioDuePortResponseBody Body;
        
        public EnvioDuePortResponse()
        {
        }
        
        public EnvioDuePortResponse(ServiceDocPortuaria.EnvioDuePortResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class EnvioDuePortResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnvioDuePortResult;
        
        public EnvioDuePortResponseBody()
        {
        }
        
        public EnvioDuePortResponseBody(string EnvioDuePortResult)
        {
            this.EnvioDuePortResult = EnvioDuePortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesDuePortRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesDuePort", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.GetMessagesDuePortRequestBody Body;
        
        public GetMessagesDuePortRequest()
        {
        }
        
        public GetMessagesDuePortRequest(ServiceDocPortuaria.GetMessagesDuePortRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMessagesDuePortRequestBody
    {
        
        public GetMessagesDuePortRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessagesDuePortResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessagesDuePortResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.GetMessagesDuePortResponseBody Body;
        
        public GetMessagesDuePortResponse()
        {
        }
        
        public GetMessagesDuePortResponse(ServiceDocPortuaria.GetMessagesDuePortResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetMessagesDuePortResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMessagesDuePortResult;
        
        public GetMessagesDuePortResponseBody()
        {
        }
        
        public GetMessagesDuePortResponseBody(string GetMessagesDuePortResult)
        {
            this.GetMessagesDuePortResult = GetMessagesDuePortResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageDuePortRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageDuePort", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.SendMessageDuePortRequestBody Body;
        
        public SendMessageDuePortRequest()
        {
        }
        
        public SendMessageDuePortRequest(ServiceDocPortuaria.SendMessageDuePortRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SendMessageDuePortRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fichero;
        
        public SendMessageDuePortRequestBody()
        {
        }
        
        public SendMessageDuePortRequestBody(string fichero)
        {
            this.fichero = fichero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageDuePortResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageDuePortResponse", Namespace="http://tempuri.org", Order=0)]
        public ServiceDocPortuaria.SendMessageDuePortResponseBody Body;
        
        public SendMessageDuePortResponse()
        {
        }
        
        public SendMessageDuePortResponse(ServiceDocPortuaria.SendMessageDuePortResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class SendMessageDuePortResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMessageDuePortResult;
        
        public SendMessageDuePortResponseBody()
        {
        }
        
        public SendMessageDuePortResponseBody(string SendMessageDuePortResult)
        {
            this.SendMessageDuePortResult = SendMessageDuePortResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    public interface DocPortuariaSoapChannel : ServiceDocPortuaria.DocPortuariaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview2.21264.1")]
    public partial class DocPortuariaSoapClient : System.ServiceModel.ClientBase<ServiceDocPortuaria.DocPortuariaSoap>, ServiceDocPortuaria.DocPortuariaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DocPortuariaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DocPortuariaSoapClient.GetBindingForEndpoint(endpointConfiguration), DocPortuariaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortuariaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DocPortuariaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortuariaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DocPortuariaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DocPortuariaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.CalculaTasaResponse ServiceDocPortuaria.DocPortuariaSoap.CalculaTasa(ServiceDocPortuaria.CalculaTasaRequest request)
        {
            return base.Channel.CalculaTasa(request);
        }
        
        public double CalculaTasa(string CodCliente, int Escala, int AñoEscala, string Operacion, string Tasa)
        {
            ServiceDocPortuaria.CalculaTasaRequest inValue = new ServiceDocPortuaria.CalculaTasaRequest();
            inValue.Body = new ServiceDocPortuaria.CalculaTasaRequestBody();
            inValue.Body.CodCliente = CodCliente;
            inValue.Body.Escala = Escala;
            inValue.Body.AñoEscala = AñoEscala;
            inValue.Body.Operacion = Operacion;
            inValue.Body.Tasa = Tasa;
            ServiceDocPortuaria.CalculaTasaResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).CalculaTasa(inValue);
            return retVal.Body.CalculaTasaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaResponse> ServiceDocPortuaria.DocPortuariaSoap.CalculaTasaAsync(ServiceDocPortuaria.CalculaTasaRequest request)
        {
            return base.Channel.CalculaTasaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaResponse> CalculaTasaAsync(string CodCliente, int Escala, int AñoEscala, string Operacion, string Tasa)
        {
            ServiceDocPortuaria.CalculaTasaRequest inValue = new ServiceDocPortuaria.CalculaTasaRequest();
            inValue.Body = new ServiceDocPortuaria.CalculaTasaRequestBody();
            inValue.Body.CodCliente = CodCliente;
            inValue.Body.Escala = Escala;
            inValue.Body.AñoEscala = AñoEscala;
            inValue.Body.Operacion = Operacion;
            inValue.Body.Tasa = Tasa;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).CalculaTasaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.CalculaTasaT0Response ServiceDocPortuaria.DocPortuariaSoap.CalculaTasaT0(ServiceDocPortuaria.CalculaTasaT0Request request)
        {
            return base.Channel.CalculaTasaT0(request);
        }
        
        public double CalculaTasaT0(string CodCliente, string CodIMO)
        {
            ServiceDocPortuaria.CalculaTasaT0Request inValue = new ServiceDocPortuaria.CalculaTasaT0Request();
            inValue.Body = new ServiceDocPortuaria.CalculaTasaT0RequestBody();
            inValue.Body.CodCliente = CodCliente;
            inValue.Body.CodIMO = CodIMO;
            ServiceDocPortuaria.CalculaTasaT0Response retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).CalculaTasaT0(inValue);
            return retVal.Body.CalculaTasaT0Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaT0Response> ServiceDocPortuaria.DocPortuariaSoap.CalculaTasaT0Async(ServiceDocPortuaria.CalculaTasaT0Request request)
        {
            return base.Channel.CalculaTasaT0Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaT0Response> CalculaTasaT0Async(string CodCliente, string CodIMO)
        {
            ServiceDocPortuaria.CalculaTasaT0Request inValue = new ServiceDocPortuaria.CalculaTasaT0Request();
            inValue.Body = new ServiceDocPortuaria.CalculaTasaT0RequestBody();
            inValue.Body.CodCliente = CodCliente;
            inValue.Body.CodIMO = CodIMO;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).CalculaTasaT0Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.CalculaTasaT1Response ServiceDocPortuaria.DocPortuariaSoap.CalculaTasaT1(ServiceDocPortuaria.CalculaTasaT1Request request)
        {
            return base.Channel.CalculaTasaT1(request);
        }
        
        public double CalculaTasaT1(string CodCliente, int Escala, int AñoEscala)
        {
            ServiceDocPortuaria.CalculaTasaT1Request inValue = new ServiceDocPortuaria.CalculaTasaT1Request();
            inValue.Body = new ServiceDocPortuaria.CalculaTasaT1RequestBody();
            inValue.Body.CodCliente = CodCliente;
            inValue.Body.Escala = Escala;
            inValue.Body.AñoEscala = AñoEscala;
            ServiceDocPortuaria.CalculaTasaT1Response retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).CalculaTasaT1(inValue);
            return retVal.Body.CalculaTasaT1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaT1Response> ServiceDocPortuaria.DocPortuariaSoap.CalculaTasaT1Async(ServiceDocPortuaria.CalculaTasaT1Request request)
        {
            return base.Channel.CalculaTasaT1Async(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.CalculaTasaT1Response> CalculaTasaT1Async(string CodCliente, int Escala, int AñoEscala)
        {
            ServiceDocPortuaria.CalculaTasaT1Request inValue = new ServiceDocPortuaria.CalculaTasaT1Request();
            inValue.Body = new ServiceDocPortuaria.CalculaTasaT1RequestBody();
            inValue.Body.CodCliente = CodCliente;
            inValue.Body.Escala = Escala;
            inValue.Body.AñoEscala = AñoEscala;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).CalculaTasaT1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.AltaBermanResponse ServiceDocPortuaria.DocPortuariaSoap.AltaBerman(ServiceDocPortuaria.AltaBermanRequest request)
        {
            return base.Channel.AltaBerman(request);
        }
        
        public string AltaBerman(int Escala, int Año, string Puerto, bool Modificada, int CodigoBGM, int Practicaje, int Electricidad)
        {
            ServiceDocPortuaria.AltaBermanRequest inValue = new ServiceDocPortuaria.AltaBermanRequest();
            inValue.Body = new ServiceDocPortuaria.AltaBermanRequestBody();
            inValue.Body.Escala = Escala;
            inValue.Body.Año = Año;
            inValue.Body.Puerto = Puerto;
            inValue.Body.Modificada = Modificada;
            inValue.Body.CodigoBGM = CodigoBGM;
            inValue.Body.Practicaje = Practicaje;
            inValue.Body.Electricidad = Electricidad;
            ServiceDocPortuaria.AltaBermanResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).AltaBerman(inValue);
            return retVal.Body.AltaBermanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.AltaBermanResponse> ServiceDocPortuaria.DocPortuariaSoap.AltaBermanAsync(ServiceDocPortuaria.AltaBermanRequest request)
        {
            return base.Channel.AltaBermanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.AltaBermanResponse> AltaBermanAsync(int Escala, int Año, string Puerto, bool Modificada, int CodigoBGM, int Practicaje, int Electricidad)
        {
            ServiceDocPortuaria.AltaBermanRequest inValue = new ServiceDocPortuaria.AltaBermanRequest();
            inValue.Body = new ServiceDocPortuaria.AltaBermanRequestBody();
            inValue.Body.Escala = Escala;
            inValue.Body.Año = Año;
            inValue.Body.Puerto = Puerto;
            inValue.Body.Modificada = Modificada;
            inValue.Body.CodigoBGM = CodigoBGM;
            inValue.Body.Practicaje = Practicaje;
            inValue.Body.Electricidad = Electricidad;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).AltaBermanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.NuevoAltaBermanResponse ServiceDocPortuaria.DocPortuariaSoap.NuevoAltaBerman(ServiceDocPortuaria.NuevoAltaBermanRequest request)
        {
            return base.Channel.NuevoAltaBerman(request);
        }
        
        public string NuevoAltaBerman(int Escala, int Año, string Puerto, bool Modificada, int CodigoBGM, int N_Atraque, string TipoAtraque, System.DateTime Ocupacion, System.DateTime Desocupacion)
        {
            ServiceDocPortuaria.NuevoAltaBermanRequest inValue = new ServiceDocPortuaria.NuevoAltaBermanRequest();
            inValue.Body = new ServiceDocPortuaria.NuevoAltaBermanRequestBody();
            inValue.Body.Escala = Escala;
            inValue.Body.Año = Año;
            inValue.Body.Puerto = Puerto;
            inValue.Body.Modificada = Modificada;
            inValue.Body.CodigoBGM = CodigoBGM;
            inValue.Body.N_Atraque = N_Atraque;
            inValue.Body.TipoAtraque = TipoAtraque;
            inValue.Body.Ocupacion = Ocupacion;
            inValue.Body.Desocupacion = Desocupacion;
            ServiceDocPortuaria.NuevoAltaBermanResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).NuevoAltaBerman(inValue);
            return retVal.Body.NuevoAltaBermanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.NuevoAltaBermanResponse> ServiceDocPortuaria.DocPortuariaSoap.NuevoAltaBermanAsync(ServiceDocPortuaria.NuevoAltaBermanRequest request)
        {
            return base.Channel.NuevoAltaBermanAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.NuevoAltaBermanResponse> NuevoAltaBermanAsync(int Escala, int Año, string Puerto, bool Modificada, int CodigoBGM, int N_Atraque, string TipoAtraque, System.DateTime Ocupacion, System.DateTime Desocupacion)
        {
            ServiceDocPortuaria.NuevoAltaBermanRequest inValue = new ServiceDocPortuaria.NuevoAltaBermanRequest();
            inValue.Body = new ServiceDocPortuaria.NuevoAltaBermanRequestBody();
            inValue.Body.Escala = Escala;
            inValue.Body.Año = Año;
            inValue.Body.Puerto = Puerto;
            inValue.Body.Modificada = Modificada;
            inValue.Body.CodigoBGM = CodigoBGM;
            inValue.Body.N_Atraque = N_Atraque;
            inValue.Body.TipoAtraque = TipoAtraque;
            inValue.Body.Ocupacion = Ocupacion;
            inValue.Body.Desocupacion = Desocupacion;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).NuevoAltaBermanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.Firma_DocumentoResponse ServiceDocPortuaria.DocPortuariaSoap.Firma_Documento(ServiceDocPortuaria.Firma_DocumentoRequest request)
        {
            return base.Channel.Firma_Documento(request);
        }
        
        public string Firma_Documento(string fichero)
        {
            ServiceDocPortuaria.Firma_DocumentoRequest inValue = new ServiceDocPortuaria.Firma_DocumentoRequest();
            inValue.Body = new ServiceDocPortuaria.Firma_DocumentoRequestBody();
            inValue.Body.fichero = fichero;
            ServiceDocPortuaria.Firma_DocumentoResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).Firma_Documento(inValue);
            return retVal.Body.Firma_DocumentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.Firma_DocumentoResponse> ServiceDocPortuaria.DocPortuariaSoap.Firma_DocumentoAsync(ServiceDocPortuaria.Firma_DocumentoRequest request)
        {
            return base.Channel.Firma_DocumentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.Firma_DocumentoResponse> Firma_DocumentoAsync(string fichero)
        {
            ServiceDocPortuaria.Firma_DocumentoRequest inValue = new ServiceDocPortuaria.Firma_DocumentoRequest();
            inValue.Body = new ServiceDocPortuaria.Firma_DocumentoRequestBody();
            inValue.Body.fichero = fichero;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).Firma_DocumentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.EnvioFTPResponse ServiceDocPortuaria.DocPortuariaSoap.EnvioFTP(ServiceDocPortuaria.EnvioFTPRequest request)
        {
            return base.Channel.EnvioFTP(request);
        }
        
        public string EnvioFTP(string fichero)
        {
            ServiceDocPortuaria.EnvioFTPRequest inValue = new ServiceDocPortuaria.EnvioFTPRequest();
            inValue.Body = new ServiceDocPortuaria.EnvioFTPRequestBody();
            inValue.Body.fichero = fichero;
            ServiceDocPortuaria.EnvioFTPResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).EnvioFTP(inValue);
            return retVal.Body.EnvioFTPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.EnvioFTPResponse> ServiceDocPortuaria.DocPortuariaSoap.EnvioFTPAsync(ServiceDocPortuaria.EnvioFTPRequest request)
        {
            return base.Channel.EnvioFTPAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.EnvioFTPResponse> EnvioFTPAsync(string fichero)
        {
            ServiceDocPortuaria.EnvioFTPRequest inValue = new ServiceDocPortuaria.EnvioFTPRequest();
            inValue.Body = new ServiceDocPortuaria.EnvioFTPRequestBody();
            inValue.Body.fichero = fichero;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).EnvioFTPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.EnvioDuePortResponse ServiceDocPortuaria.DocPortuariaSoap.EnvioDuePort(ServiceDocPortuaria.EnvioDuePortRequest request)
        {
            return base.Channel.EnvioDuePort(request);
        }
        
        public string EnvioDuePort(string fichero)
        {
            ServiceDocPortuaria.EnvioDuePortRequest inValue = new ServiceDocPortuaria.EnvioDuePortRequest();
            inValue.Body = new ServiceDocPortuaria.EnvioDuePortRequestBody();
            inValue.Body.fichero = fichero;
            ServiceDocPortuaria.EnvioDuePortResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).EnvioDuePort(inValue);
            return retVal.Body.EnvioDuePortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.EnvioDuePortResponse> ServiceDocPortuaria.DocPortuariaSoap.EnvioDuePortAsync(ServiceDocPortuaria.EnvioDuePortRequest request)
        {
            return base.Channel.EnvioDuePortAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.EnvioDuePortResponse> EnvioDuePortAsync(string fichero)
        {
            ServiceDocPortuaria.EnvioDuePortRequest inValue = new ServiceDocPortuaria.EnvioDuePortRequest();
            inValue.Body = new ServiceDocPortuaria.EnvioDuePortRequestBody();
            inValue.Body.fichero = fichero;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).EnvioDuePortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.GetMessagesDuePortResponse ServiceDocPortuaria.DocPortuariaSoap.GetMessagesDuePort(ServiceDocPortuaria.GetMessagesDuePortRequest request)
        {
            return base.Channel.GetMessagesDuePort(request);
        }
        
        public string GetMessagesDuePort()
        {
            ServiceDocPortuaria.GetMessagesDuePortRequest inValue = new ServiceDocPortuaria.GetMessagesDuePortRequest();
            inValue.Body = new ServiceDocPortuaria.GetMessagesDuePortRequestBody();
            ServiceDocPortuaria.GetMessagesDuePortResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).GetMessagesDuePort(inValue);
            return retVal.Body.GetMessagesDuePortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.GetMessagesDuePortResponse> ServiceDocPortuaria.DocPortuariaSoap.GetMessagesDuePortAsync(ServiceDocPortuaria.GetMessagesDuePortRequest request)
        {
            return base.Channel.GetMessagesDuePortAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.GetMessagesDuePortResponse> GetMessagesDuePortAsync()
        {
            ServiceDocPortuaria.GetMessagesDuePortRequest inValue = new ServiceDocPortuaria.GetMessagesDuePortRequest();
            inValue.Body = new ServiceDocPortuaria.GetMessagesDuePortRequestBody();
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).GetMessagesDuePortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceDocPortuaria.SendMessageDuePortResponse ServiceDocPortuaria.DocPortuariaSoap.SendMessageDuePort(ServiceDocPortuaria.SendMessageDuePortRequest request)
        {
            return base.Channel.SendMessageDuePort(request);
        }
        
        public string SendMessageDuePort(string fichero)
        {
            ServiceDocPortuaria.SendMessageDuePortRequest inValue = new ServiceDocPortuaria.SendMessageDuePortRequest();
            inValue.Body = new ServiceDocPortuaria.SendMessageDuePortRequestBody();
            inValue.Body.fichero = fichero;
            ServiceDocPortuaria.SendMessageDuePortResponse retVal = ((ServiceDocPortuaria.DocPortuariaSoap)(this)).SendMessageDuePort(inValue);
            return retVal.Body.SendMessageDuePortResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceDocPortuaria.SendMessageDuePortResponse> ServiceDocPortuaria.DocPortuariaSoap.SendMessageDuePortAsync(ServiceDocPortuaria.SendMessageDuePortRequest request)
        {
            return base.Channel.SendMessageDuePortAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceDocPortuaria.SendMessageDuePortResponse> SendMessageDuePortAsync(string fichero)
        {
            ServiceDocPortuaria.SendMessageDuePortRequest inValue = new ServiceDocPortuaria.SendMessageDuePortRequest();
            inValue.Body = new ServiceDocPortuaria.SendMessageDuePortRequestBody();
            inValue.Body.fichero = fichero;
            return ((ServiceDocPortuaria.DocPortuariaSoap)(this)).SendMessageDuePortAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocPortuariaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DocPortuariaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocPortuariaSoap))
            {
                //return new System.ServiceModel.EndpointAddress("http://localhost:3332/DocPortuaria.asmx");
                return new System.ServiceModel.EndpointAddress("http://fo9187:5034/SWDocPortuaria/DocPortuaria.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DocPortuariaSoap12))
            {
                //return new System.ServiceModel.EndpointAddress("http://localhost:3332/DocPortuaria.asmx");
                return new System.ServiceModel.EndpointAddress("http://fo9187:5034/SWDocPortuaria/DocPortuaria.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DocPortuariaSoap,
            
            DocPortuariaSoap12,
        }
    }
}
